# Generated by Django 3.0.8 on 2020-07-14 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='asset_class',
        ),
        migrations.AlterField(
            model_name='assetclass',
            name='asset_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='assets.AssetType'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='assets.Asset'),
        ),
    ]
